name: Generate Snake Animation

on:
  # Run automatically every day
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual workflow runs
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v3
      
      # Generates the snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: sntsjohan
          # Output directory for the animation
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Generate snake animation from GitHub contributions
          gif_out_path: dist/github-contribution-grid-snake.gif
      
      # Push the changes
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # The branch where the animation will be generated
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
